//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recruitment_Portal.ScheduleInterview {
    using System.Web.UI.WebControls.Expressions;
    using System.Web.UI.HtmlControls;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.SessionState;
    using System.Configuration;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Collections.Specialized;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    
    
    public partial class ScheduleInterview {
        
        public static implicit operator global::System.Web.UI.TemplateControl(ScheduleInterview target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControlTree(global::Recruitment_Portal.ScheduleInterview.ScheduleInterview @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n\r\n\r\n\r\n<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery." +
                        "min.js\"></script>\r\n<script type=\"text/javascript\" src=\"http://maxcdn.bootstrapcd" +
                        "n.com/bootstrap/3.3.1/js/bootstrap.min.js\"></script>\r\n<script src=\"http://cdnjs." +
                        "cloudflare.com/ajax/libs/moment.js/2.9.0/moment-with-locales.js\"></script>\r\n<scr" +
                        "ipt src=\"http://cdn.rawgit.com/Eonasdan/bootstrap-datetimepicker/e8bddc60e73c1ec" +
                        "2475f827be36e1957af72e2ea/src/js/bootstrap-datetimepicker.js\"></script>\r\n<script" +
                        " type=\'text/javascript\' src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery-ajaxt" +
                        "ransport-xdomainrequest/1.0.1/jquery.xdomainrequest.min.js\"></script>\r\n<script t" +
                        "ype=\"text/javascript\" src=\"../_layouts/15/clientforms.js\">  </script>\r\n<script t" +
                        "ype=\"text/javascript\" src=\"../_layouts/15/clienttemplates.js\">  </script>\r\n<scri" +
                        "pt type=\"text/javascript\" src=\"../_layouts/15/clientpeoplepicker.js\"></script>\r\n" +
                        "<script type=\"text/javascript\" src=\"../_layouts/15/autofill.js\"></script>\r\n<scri" +
                        "pt type=\"text/javascript\" src=\"../_layouts/15/1033/strings.js\"></script>\r\n\r\n<scr" +
                        "ipt type=\"text/javascript\">\r\n    var vacanies = \"\";\r\n    var candidates = \"\";\r\n " +
                        "   var CoInnovators_user_info_people = \"\";\r\n    var CoInnovators = \"\";\r\n\r\n    $(" +
                        "document).ready(function () {\r\n\r\n        initializePeoplePicker(\'CoInnovators\');" +
                        "\r\n        //SaveScheduleInterview();\r\n        PopulateVacancy();\r\n        // ale" +
                        "rt(\'hi\');\r\n\r\n        $(\"#btnsubmit\").click(function () {\r\n            SaveSchedu" +
                        "leInterview();\r\n        });\r\n\r\n\r\n    });\r\n    function SaveScheduleInterview(use" +
                        "rid) {\r\n        var VacancyName = $(\'#drpVacancyName option:selected\').text();\r\n" +
                        "        var CandidateName = $(\'#txtName option:selected\').text();\r\n        //var" +
                        " Interviewer = $(\'#CoInnovators\').userid;\r\n        var InterviewDate = $(\'#datet" +
                        "imepicker\').find(\"input\").val();\r\n        var Remarks = $(\'#txtRemarks\').val();\r" +
                        "\n        var Status = $(\'#drpStatus option:selected\').val();\r\n        getUserInf" +
                        "o(\"CoInnovators\");\r\n\r\n        getVacancyId(VacancyName);\r\n        GetCandidateNa" +
                        "meId(CandidateName);\r\n        $.ajax({\r\n            url: _spPageContextInfo.webA" +
                        "bsoluteUrl + \"/_api/web/lists/GetByTitle(\'ScheduleInterview\')/items\",\r\n         " +
                        "   type: \"POST\",\r\n            data: JSON.stringify({\r\n                \'__metadat" +
                        "a\': { \'type\': \'SP.Data.ScheduleInterviewListItem\' },\r\n                \'VacancyId" +
                        "\': vacanies,\r\n                \'CandidateNameId\': candidates,\r\n                \'I" +
                        "nterviewersId\': CoInnovators_user_info_people,\r\n                \'InterviewDate\':" +
                        " InterviewDate,\r\n                \'Remarks\': Remarks,\r\n                \'Status\': " +
                        "Status,\r\n            }),\r\n            async: false,\r\n\r\n            headers: {\r\n " +
                        "               \"Accept\": \"application/json;odata=verbose\",\r\n                \"con" +
                        "tent-type\": \"application/json; odata=verbose\",\r\n                \"X-RequestDigest" +
                        "\": $(\"#__REQUESTDIGEST\").val()\r\n            },\r\n            success: function (d" +
                        "ata) {\r\n                alert(\"Scheduled Interview Successfully\");\r\n            " +
                        "    $(\'#drpVacancyName option:selected\').html(\'select\');\r\n                $(\'#tx" +
                        "tName option:selected\').html(\'select\');\r\n                $(\'#CoInnovators\').val(" +
                        "\'\');\r\n                $(\'#InterviewDate\').val(\'\');\r\n                $(\'#txtRemar" +
                        "ks\').val(\'\');\r\n                $(\'#drpStatus\').val(\'\');\r\n                locatio" +
                        "n.href = _spPageContextInfo.webAbsoluteUrl + \"/Pages/ScheduleInterview.aspx\";\r\n\r" +
                        "\n            },\r\n            error: function (err) {\r\n                alert(\"Err" +
                        "or while adding item: \" + JSON.stringify(err));\r\n\r\n            }\r\n\r\n        });\r" +
                        "\n    }\r\n\r\n    function getVacancyId(result) {\r\n        vacanies = \"\";\r\n        $" +
                        ".ajax({\r\n            url: _spPageContextInfo.webAbsoluteUrl + \"/_api/web/lists/g" +
                        "etbytitle(\'Vacancies\')/items?$filter=VacancyName eq \'\" + result + \"\'\",\r\n        " +
                        "    type: \"GET\",\r\n            async: false,\r\n            headers: {\r\n           " +
                        "     \"accept\": \"application/json;odata=verbose\",\r\n            },\r\n            su" +
                        "ccess: function (data) {\r\n                if (data.d.results) {\r\n               " +
                        "     vacanies = data.d.results[0].ID;\r\n                }\r\n\r\n            },\r\n    " +
                        "        error: function (error) {\r\n                alert(JSON.stringify(error));" +
                        "\r\n            }\r\n        });\r\n    }\r\n\r\n    function GetCandidateNameId(result) {" +
                        "\r\n        candidates = \"\";\r\n        $.ajax({\r\n            url: _spPageContextInf" +
                        "o.webAbsoluteUrl + \"/_api/web/lists/getbytitle(\'Candidates\')/items?$select=ID,Ca" +
                        "ndidateName,VacancyName/Id,VacancyName/VacancyName&$expand=VacancyName&$filter=C" +
                        "andidateName eq \'\" + result + \"\'\",\r\n            type: \"GET\",\r\n            async:" +
                        " false,\r\n            headers: {\r\n                \"accept\": \"application/json;oda" +
                        "ta=verbose\",\r\n            },\r\n            success: function (data) {\r\n          " +
                        "      if (data.d.results) {\r\n                    candidates = data.d.results[0]." +
                        "ID;\r\n                }\r\n\r\n            },\r\n            error: function (error) {\r" +
                        "\n                alert(JSON.stringify(error));\r\n            }\r\n        });\r\n    " +
                        "}\r\n\r\n\r\n\r\n    function PopulateVacancy() {\r\n        var listName = \"Vacancies\";\r\n" +
                        "        var url = _spPageContextInfo.webAbsoluteUrl;\r\n        getVacancy(listNam" +
                        "e, url, function (data) {\r\n            var items = data.d.results;\r\n            " +
                        "$(\'#drpVacancyName\').find(\'option\').remove().end();\r\n            var inputElemen" +
                        "t = \'<option>select</option>\';\r\n            for (var i = 0; i < items.length; i+" +
                        "+) {\r\n                var itemId = items[i].Id,\r\n                  itemVal = ite" +
                        "ms[i].VacancyName;\r\n                inputElement += \'<option value=\"\' + itemId +" +
                        " \'\">\' + itemVal + \'</option>\';\r\n            }\r\n            $(\'#drpVacancyName\')." +
                        "append(inputElement);\r\n            $(\"#drpVacancyName\").each(function () {\r\n    " +
                        "            $(\'option\', this).each(function () {\r\n\r\n                    if ($(th" +
                        "is).text() == \'Select\') {\r\n                        $(this).attr(\'selected\', \'sel" +
                        "ected\')\r\n                    };\r\n                });\r\n            });\r\n         " +
                        "   $(\'#drpVacancyName\').on(\'change\', function () {\r\n                var selected" +
                        "country = $(\"#drpVacancyName option:selected\").val();\r\n                getCandid" +
                        "ate(\'Candidates\', url, selectedcountry, function (data) {\r\n                    v" +
                        "ar items = data.d.results;\r\n                    //$(\'#drpVacancyName\').find(\'opt" +
                        "ion\').remove().end();\r\n                    var inputElement = \'<option>select</o" +
                        "ption>\';\r\n                    for (var i = 0; i < items.length; i++) {\r\n        " +
                        "                var itemId = items[i].CandidateName,\r\n                          " +
                        "itemVal = items[i].CandidateName;\r\n                        inputElement += \'<opt" +
                        "ion value=\"\' + itemId + \'\">\' + itemVal + \'</option>\';\r\n                    }\r\n\r\n" +
                        "                    $(\'#txtName\').append(inputElement);\r\n                    $(\"" +
                        "#txtName\").each(function () {\r\n                        $(\'option\', this).each(fu" +
                        "nction () {\r\n\r\n                            if ($(this).text() == \'Select\') {\r\n  " +
                        "                              $(this).attr(\'selected\', \'selected\')\r\n            " +
                        "                };\r\n                        });\r\n                    });\r\n      " +
                        "          }, function (data) {\r\n                    alert(\'An error occured whil" +
                        "e getting client. Please try again\');\r\n                });\r\n            });\r\n\r\n " +
                        "       }, function (data) {\r\n            alert(\"An error occured while getting p" +
                        "roject. Please try again\");\r\n        });\r\n    }\r\n\r\n    function getVacancy(listN" +
                        "ame, siteurl, success, failure) {\r\n        $.ajax({\r\n            url: siteurl + " +
                        "\"/_api/web/lists/getbytitle(\'\" + listName + \"\')/items?$select=VacancyName,ID\",\r\n" +
                        "            method: \"GET\",\r\n            headers: { \"Accept\": \"application/json; " +
                        "odata=verbose\" },\r\n            success: function (data) {\r\n                succe" +
                        "ss(data);\r\n            },\r\n            error: function (data) {\r\n               " +
                        " failure(data);\r\n            }\r\n        });\r\n    }\r\n\r\n    function getCandidate(" +
                        "listName, siteurl, selectedcountryid, success, failure) {\r\n        var url = sit" +
                        "eurl + \"/_api/web/lists/getbytitle(\'\" + listName + \"\')/items?$select=ID,Candidat" +
                        "eName,VacancyName/Id,VacancyName/VacancyName&$expand=VacancyName&$filter=Vacancy" +
                        "Name eq \'\" + selectedcountryid + \"\'\";\r\n        $.ajax({\r\n            url: url,\r\n" +
                        "            method: \"GET\",\r\n            headers: { \"Accept\": \"application/json; " +
                        "odata=verbose\" },\r\n            success: function (data) {\r\n                succe" +
                        "ss(data);\r\n            },\r\n            error: function (data) {\r\n               " +
                        " failure(data);\r\n            }\r\n        });\r\n    }\r\n\r\n    function postvalueinto" +
                        "list() {\r\n        getUserInfo(\'CoInnovators\');\r\n        var requestUri = _spPage" +
                        "ContextInfo.webAbsoluteUrl + \"/_api/web/lists/getByTitle(\'\" + submitlistname + \"" +
                        "\')/items\";\r\n        var coinnovator = CoInnovators_user_info_people;\r\n        $." +
                        "ajax(\r\n              {\r\n                  url: requestUri,\r\n                  as" +
                        "ync: false,\r\n                  type: \"POST\",\r\n                  data: JSON.strin" +
                        "gify({\r\n                      \'__metadata\': { \'type\': \'SP.Data.\' + submitlistint" +
                        "name + \'ListItem\' },\r\n                      \'Title\': \"Test\",\r\n                  " +
                        "    \'Co_InnovatorsId\': {\r\n                          results: CoInnovators_user_i" +
                        "nfo_people\r\n                      }\r\n                  }),\r\n                  he" +
                        "aders: {\r\n                      \"Accept\": \"application/json;odata=verbose\",\r\n   " +
                        "                   \"content-type\": \"application/json; odata=verbose\",\r\n         " +
                        "             \"X-RequestDigest\": $(\"#__REQUESTDIGEST\").val(),\r\n                  " +
                        "    // \"X-HTTP-Method\": \"MERGE\",\r\n                      // \"If-Match\": \"*\"\r\n    " +
                        "              },\r\n                  success: function (data) {\r\n\r\n              " +
                        "        submitid = data.d.Id;\r\n                      alert(submitid);\r\n\r\n       " +
                        "           },\r\n                  error: function (err) {\r\n                      " +
                        "alert(\"Delete List Item Error Message: \" + JSON.stringify(err));\r\n              " +
                        "        console.log(\"Delete List Item Error Message: \" + JSON.stringify(err));\r\n" +
                        "                  }\r\n              });\r\n\r\n    }\r\n    function initializePeoplePi" +
                        "cker(peoplePickerElementId) {\r\n\r\n        // Create a schema to store picker prop" +
                        "erties, and set the properties.\r\n        var schema = {};\r\n        schema[\'Princ" +
                        "ipalAccountType\'] = \'User,DL,SecGroup,SPGroup\';\r\n        schema[\'SearchPrincipal" +
                        "Source\'] = 15;\r\n        schema[\'ResolvePrincipalSource\'] = 15;\r\n        schema[\'" +
                        "AllowMultipleValues\'] = true;\r\n        schema[\'MaximumEntitySuggestions\'] = 50;\r" +
                        "\n        schema[\'Width\'] = \'100%\';\r\n\r\n        // Render and initialize the picke" +
                        "r.\r\n        // Pass the ID of the DOM element that contains the picker, an array" +
                        " of initial\r\n        // PickerEntity objects to set the picker value, and a sche" +
                        "ma that defines\r\n        // picker properties.\r\n        this.SPClientPeoplePicke" +
                        "r_InitStandaloneControlWrapper(peoplePickerElementId, null, schema);\r\n\r\n    }\r\n\r" +
                        "\n    // Query the picker for user information.\r\n    function getUserInfo(peopleP" +
                        "ickerDiv) {\r\n        // Get the people picker object from the page.\r\n        var" +
                        " people = peoplePickerDiv + \"_TopSpan\";\r\n        var peoplePicker = this.SPClien" +
                        "tPeoplePicker.SPClientPeoplePickerDict[people];\r\n        // Get user keys.\r\n    " +
                        "    var keys = peoplePicker.GetAllUserKeys();\r\n\r\n        GetUserId(keys, peopleP" +
                        "ickerDiv);\r\n    }\r\n    // Submit view user info starts\r\n    function GetUserId(u" +
                        "serName, itemname) {\r\n\r\n\r\n        var siteUrl = _spPageContextInfo.siteAbsoluteU" +
                        "rl;\r\n        var accountName = userName;\r\n        if (accountName != \"\") {\r\n    " +
                        "        $.ajax({\r\n                url: siteUrl + \"/_api/web/siteusers(@v)?@v=\'\" " +
                        "+\r\n                    encodeURIComponent(accountName) + \"\'\",\r\n                m" +
                        "ethod: \"GET\",\r\n                async: false,\r\n                headers: { \"Accept" +
                        "\": \"application/json; odata=verbose\" },\r\n                success: function (data" +
                        ") {\r\n                    ///popup user id received from site users.\r\n           " +
                        "         if (data.d) {\r\n                        if (itemname == \"CoInnovators\") " +
                        "{\r\n\r\n                            CoInnovators_user_info_people = data.d.Id;\r\n   " +
                        "                     }\r\n                    }\r\n                },\r\n             " +
                        "   error: function (data) {\r\n                    console.log(JSON.stringify(data" +
                        "));\r\n                }\r\n            });\r\n        }\r\n\r\n    }\r\n\r\n\r\n</script>\r\n<lin" +
                        "k rel=\"stylesheet\" type=\"text/css\" media=\"screen\" href=\"http://maxcdn.bootstrapc" +
                        "dn.com/bootstrap/3.3.1/css/bootstrap.min.css\" />\r\n<link rel=\"stylesheet\" href=\"h" +
                        "ttp://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css\">\r\n<li" +
                        "nk href=\"http://cdn.rawgit.com/Eonasdan/bootstrap-datetimepicker/e8bddc60e73c1ec" +
                        "2475f827be36e1957af72e2ea/build/css/bootstrap-datetimepicker.css\" rel=\"styleshee" +
                        "t\">\r\n\r\n<script type=\"text/javascript\">\r\n    $(document).ready(function () {\r\n   " +
                        "     $(\'#datetimepicker5\').datetimepicker({\r\n            defaultDate: \"11/1/2013" +
                        "\",\r\n            disabledDates: [\r\n                moment(\"12/25/2013\"),\r\n       " +
                        "         new Date(2013, 11 - 1, 21),\r\n                \"11/22/2013 00:53\"\r\n      " +
                        "      ]\r\n        });\r\n    });\r\n</script>\r\n<script type=\"text/javascript\">\r\n    $" +
                        "(function () {\r\n        $(\'#datetimepicker1\').datetimepicker();\r\n    });\r\n</scri" +
                        "pt>\r\n\r\n\r\n    <div class=\"col-md-9 inner_cont\">\r\n        <div class=\"form-horizon" +
                        "tal submt_form top-buffer\">\r\n\r\n            <div class=\"form-group\">\r\n\r\n         " +
                        "       <label id=\"lblVacancyName\" class=\"col-md-6\">Vacancy Name</label>\r\n       " +
                        "         <div class=\"col-md-6\">\r\n                    <select id=\"drpVacancyName\"" +
                        " class=\"form-control\">\r\n                    </select>\r\n                </div>\r\n " +
                        "           </div>\r\n\r\n\r\n\r\n            <div class=\"form-group\">\r\n                <" +
                        "label id=\"lblcandidatename\" class=\"col-md-6\">Candidate Name</label>\r\n           " +
                        "     <div class=\"col-md-6\">\r\n                    <select id=\"txtName\" class=\"for" +
                        "m-control\">\r\n                    </select>\r\n                </div>\r\n            " +
                        "</div>\r\n\r\n\r\n\r\n            <div class=\"form-group\">\r\n                <label id=\"l" +
                        "blinterviewer\" class=\"col-md-6\">Interviewer</label>\r\n                <div class=" +
                        "\"col-md-6\">\r\n                    <div id=\"CoInnovators\" class=\"Test\"></div>\r\n   " +
                        "             </div>\r\n            </div>\r\n\r\n\r\n\r\n            <div class=\"form-grou" +
                        "p\">\r\n                <label id=\"lblInterviewDate\" class=\"col-md-6\">Interview Dat" +
                        "e</label>\r\n                <div class=\"col-md-6\">\r\n                    <div clas" +
                        "s=\'input-group date\' id=\'datetimepicker5\'>\r\n                        <input type=" +
                        "\'text\' class=\"form-control\" />\r\n                        <span class=\"input-group" +
                        "-addon\">\r\n                            <span class=\"glyphicon glyphicon-calendar\"" +
                        "></span>\r\n                        </span>\r\n                    </div>\r\n         " +
                        "       </div>\r\n            </div>\r\n\r\n            <div class=\"form-group\">\r\n     " +
                        "           <label id=\"LabelRemarks\" class=\"col-md-6\">Remarks</label>\r\n          " +
                        "      <div class=\"col-md-6\">\r\n                    <input type=\"text\" id=\"txtRema" +
                        "rks\" class=\"form-control\" />\r\n\r\n                </div>\r\n            </div>\r\n\r\n\r\n" +
                        "            <div class=\"form-group\">\r\n                <label id=\"LabelStatus\" cl" +
                        "ass=\"col-md-6\">Status</label>\r\n\r\n                <div class=\"col-md-6\">\r\n       " +
                        "             <select id=\"drpStatus\" class=\"form-control\">\r\n                     " +
                        "   <option>select</option>\r\n                        <option>Completed</option>\r\n" +
                        "                        <option>Not Completed</option>\r\n                    </se" +
                        "lect>\r\n\r\n                </div>\r\n            </div>\r\n\r\n\r\n\r\n            <ul class" +
                        "=\"pull-right list-inline\">\r\n                <li>\r\n                    <input typ" +
                        "e=\"button\" id=\"btnsubmit\" class=\"btn btn-default blu_btn\" value=\"Submit\" />\r\n\r\n " +
                        "               <li>\r\n                    <input type=\"button\" id=\"btnclear\" clas" +
                        "s=\"btn btn-default blu_btn\" value=\"Cancel\" />\r\n            </ul>\r\n        </div>" +
                        "\r\n    </div>\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n   \r\n\r\n"));
        }
        
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
